### ISSUE TITLE
`Segmentation fault (core dumped)` when running a simple example

### ISSUE THREAD

**Issue by andheroe** [durner/AnyBlob#11]
I've downloaded the repo and executed commands in the readme of the Simple example:  https://github.com/durner/AnyBlob/blob/master/example/simple/README.md on a fresh EC2 Ubuntu instance in AWS.
The build was successful.
Then I executed the built binary `./SimpleAnyBlob` which resulted in `Segmentation fault (core dumped)`.
After some debugging I located the line in `main.cpp` of the simple example that causes this error: https://github.com/durner/AnyBlob/blob/master/example/simple/main.cpp#L29

How do I fix this?
Thanks

**Comment by durner** [comment]
The simple example won't work out-of-the-box. You need to specify a real object in your S3 object storage that you would like to access (L18 and L19). Moreover, you need to either configure your AWS EC2 instance to allow accessing S3 via the automatic key exchange to the instance^1, or specify your S3 API key in the call to makeProvider (L29).

The segfault was probably caused by throwing an uncatched "Invalid HttpResponse: Incomplete header!" exception. But I agree that the example should handle the bad path as well and catch the exception. Overall, better documentation is on the roadmap as soon as I have more time to spare for AnyBlob.

^1 https://repost.aws/knowledge-center/ec2-instance-access-s3-bucket
